### PR TITLE
add download-dialog plugin

### PR DESCRIPTION
**Pull request by worlword**
This allows users to click a download-button in the toolbar. On Button-
Click the user will be presented with files from the currently
loaded chat-history. The user can choose which files to download.
All selected files will be packaged in a zip-file and can be downloaded
via browser dialog.

So, the last pull-Request, for now :D
As the description above states, this allows you to download all/many files from the chat-history in one go. This is an old feature from a converse 3.X version, which I migrated to the current version. I know, you have created your own download-option now for files in the chat in the meantime. So the main question is, if you are interested in this feature.
It adds a download-button to the toolbar.

When the user clicks on the button, the chat-history will be searched for files to download. Which files can be downloaded depends on the allowed_download_servers-Parameter. This parameter was needed to identify what is a file and what is just text. It also allows to prevent youtube-links and other stuff to be included accidentally into the download-dialog.

When files are found inside the chat-history, the download-dialog will open. Here the user can select/deselect files, change their names, etc. When the user clicks download, all files will be packed into a zip-file and the browser-download-dialog appears.

This is the same plugin as it was discussed in https://github.com/conversejs/converse.js/pull/1645.
The readme.md-file contains the necessary information.

### CODE REVIEW

**Comment by licaon-kter** [comment]
How far does it go in time to gather files? 1 day? 1 month? 1 year?

**Comment by deleolajide** [comment]
> How far does it go in time to gather files? 1 day? 1 month? 1 year?

For the code, it looks like it just scans whatever is in the chat history in converse. It does not seem to do a MAM query.

**Comment by worlword** [comment]
Yes. It only takes what is inside the chat-history. So when you scroll up you can get older files.

**Comment by deleolajide** [comment]
You might want to consider improving it to use a MAM request independent of the chat history in order to work with the **clear history on connection** setting of Converse. Also, only showing files that have a working link as some HTTP file uploads expire.

@worlword , It is a very good plugin. Thanks for the contribution

**Pull request merged**
